version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:bionic

    steps:
      - checkout

      - run:
          name: Greeting
          command: echo Hello, world.

      - run:
          name: Print the Current Time
          command: date

      - run: sudo apt update && sudo apt install -y libjansson4 libjansson-dev
      - run:
          name: Runnning tests
          command: make test
